-- MySQL Script generated by MySQL Workbench
-- Thu Jun 22 16:20:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Local` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Nome_UNIQUE` ON `mydb`.`Departamento` (`Nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Departamento` VARCHAR(50) NOT NULL,
  `Semestres` TINYINT(1) NOT NULL,
  `Carga Horaria` DECIMAL(1,3) NOT NULL,
  `Localidade` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `Nome`, `Departamento_idDepartamento`),
  CONSTRAINT `fk_Curso_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCurso_UNIQUE` ON `mydb`.`Curso` (`idCurso` ASC) VISIBLE;

CREATE UNIQUE INDEX `Nome_UNIQUE` ON `mydb`.`Curso` (`Nome` ASC) VISIBLE;

CREATE INDEX `fk_Curso_Departamento1_idx` ON `mydb`.`Curso` (`Departamento_idDepartamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Curso` VARCHAR(70) NOT NULL,
  `Qtd_Aulas` TINYINT(2) NOT NULL,
  `Departamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idDisciplina_UNIQUE` ON `mydb`.`Disciplina` (`idDisciplina` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pertence / Detem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pertence / Detem` (
  `Curso_idCurso` INT NOT NULL,
  `Curso_Nome` VARCHAR(70) NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Curso_idCurso`, `Curso_Nome`, `Disciplina_idDisciplina`),
  CONSTRAINT `fk_Curso_has_Disciplina_Curso1`
    FOREIGN KEY (`Curso_idCurso` , `Curso_Nome`)
    REFERENCES `mydb`.`Curso` (`idCurso` , `Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Curso_has_Disciplina_Disciplina1_idx` ON `mydb`.`Pertence / Detem` (`Disciplina_idDisciplina` ASC) VISIBLE;

CREATE INDEX `fk_Curso_has_Disciplina_Curso1_idx` ON `mydb`.`Pertence / Detem` (`Curso_idCurso` ASC, `Curso_Nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT(5) NOT NULL,
  `Matricula` INT(9) NOT NULL,
  PRIMARY KEY (`idAluno`, `Matricula`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idAluno_UNIQUE` ON `mydb`.`Aluno` (`idAluno` ASC) VISIBLE;

CREATE UNIQUE INDEX `Matricula_UNIQUE` ON `mydb`.`Aluno` (`Matricula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idAluno` INT(5) NOT NULL,
  `Matricula_Professor` INT(9) NOT NULL,
  `idDepartamento` INT NOT NULL,
  `idDepartamento1` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `Matricula_Professor`, `idDepartamento`, `idDepartamento1`),
  CONSTRAINT `fk_Professor_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Departamento2`
    FOREIGN KEY (`idDepartamento1`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idAluno_UNIQUE` ON `mydb`.`Professor` (`idAluno` ASC) VISIBLE;

CREATE UNIQUE INDEX `Matricula_UNIQUE` ON `mydb`.`Professor` (`Matricula_Professor` ASC) VISIBLE;

CREATE INDEX `fk_Professor_Departamento1_idx` ON `mydb`.`Professor` (`idDepartamento` ASC) VISIBLE;

CREATE INDEX `fk_Professor_Departamento2_idx` ON `mydb`.`Professor` (`idDepartamento1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(80) NOT NULL,
  `Telefone` VARCHAR(12) NULL,
  `Data Nasc` DATE NOT NULL,
  `Aluno_copy1_copy1_copy1_idAluno` INT(5) NOT NULL,
  `Aluno_copy1_copy1_copy1_Matricula` INT(9) NOT NULL,
  `Aluno_copy1_copy1_copy1_copy1_idAluno` INT(5) NOT NULL,
  `Aluno_copy1_copy1_copy1_copy1_Matricula_Professor` INT(9) NOT NULL,
  PRIMARY KEY (`idPessoa`),
  CONSTRAINT `fk_Pessoa_Aluno_copy1_copy1_copy11`
    FOREIGN KEY (`Aluno_copy1_copy1_copy1_idAluno` , `Aluno_copy1_copy1_copy1_Matricula`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Aluno_copy1_copy1_copy1_copy11`
    FOREIGN KEY (`Aluno_copy1_copy1_copy1_copy1_idAluno` , `Aluno_copy1_copy1_copy1_copy1_Matricula_Professor`)
    REFERENCES `mydb`.`Professor` (`idAluno` , `Matricula_Professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProfessor_UNIQUE` ON `mydb`.`Pessoa` (`idPessoa` ASC) VISIBLE;

CREATE INDEX `fk_Pessoa_Aluno_copy1_copy1_copy11_idx` ON `mydb`.`Pessoa` (`Aluno_copy1_copy1_copy1_idAluno` ASC, `Aluno_copy1_copy1_copy1_Matricula` ASC) VISIBLE;

CREATE INDEX `fk_Pessoa_Aluno_copy1_copy1_copy1_copy11_idx` ON `mydb`.`Pessoa` (`Aluno_copy1_copy1_copy1_copy1_idAluno` ASC, `Aluno_copy1_copy1_copy1_copy1_Matricula_Professor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Leciona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Leciona` (
  `Professor_idAluno` INT(5) NOT NULL,
  `Professor_Matricula_Professor` INT(9) NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Professor_idAluno`, `Professor_Matricula_Professor`, `Disciplina_idDisciplina`),
  CONSTRAINT `fk_Professor_has_Disciplina_Professor1`
    FOREIGN KEY (`Professor_idAluno` , `Professor_Matricula_Professor`)
    REFERENCES `mydb`.`Professor` (`idAluno` , `Matricula_Professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Professor_has_Disciplina_Disciplina1_idx` ON `mydb`.`Leciona` (`Disciplina_idDisciplina` ASC) VISIBLE;

CREATE INDEX `fk_Professor_has_Disciplina_Professor1_idx` ON `mydb`.`Leciona` (`Professor_idAluno` ASC, `Professor_Matricula_Professor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Matriculado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matriculado` (
  `Aluno_idAluno` INT(5) NOT NULL,
  `Aluno_Matricula` INT(9) NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Aluno_Matricula`, `Disciplina_idDisciplina`),
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Matricula`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` ON `mydb`.`Matriculado` (`Disciplina_idDisciplina` ASC) VISIBLE;

CREATE INDEX `fk_Aluno_has_Disciplina_Aluno1_idx` ON `mydb`.`Matriculado` (`Aluno_idAluno` ASC, `Aluno_Matricula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Graduando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Graduando` (
  `Aluno_idAluno` INT(5) NOT NULL,
  `Aluno_Matricula` INT(9) NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Curso_Nome` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Aluno_Matricula`, `Curso_idCurso`, `Curso_Nome`),
  CONSTRAINT `fk_Aluno_has_Curso_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Matricula`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Curso_Curso1`
    FOREIGN KEY (`Curso_idCurso` , `Curso_Nome`)
    REFERENCES `mydb`.`Curso` (`idCurso` , `Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Aluno_has_Curso_Curso1_idx` ON `mydb`.`Graduando` (`Curso_idCurso` ASC, `Curso_Nome` ASC) VISIBLE;

CREATE INDEX `fk_Aluno_has_Curso_Aluno1_idx` ON `mydb`.`Graduando` (`Aluno_idAluno` ASC, `Aluno_Matricula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina_has_Requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina_has_Requisitos` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Disciplina_idDisciplina1` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Disciplina_idDisciplina1`),
  CONSTRAINT `fk_Disciplina_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Disciplina_Disciplina2`
    FOREIGN KEY (`Disciplina_idDisciplina1`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Disciplina_has_Disciplina_Disciplina2_idx` ON `mydb`.`Disciplina_has_Requisitos` (`Disciplina_idDisciplina1` ASC) VISIBLE;

CREATE INDEX `fk_Disciplina_has_Disciplina_Disciplina1_idx` ON `mydb`.`Disciplina_has_Requisitos` (`Disciplina_idDisciplina` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto_Extensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto_Extensao` (
  `idProjeto_Extensao` INT NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Localidade` VARCHAR(45) NOT NULL,
  `Area de Estudo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProjeto_Extensao`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProjeto_Extensao_UNIQUE` ON `mydb`.`Projeto_Extensao` (`idProjeto_Extensao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participa` (
  `Projeto_Extensao_idProjeto_Extensao` INT NOT NULL,
  `Aluno_idAluno` INT(5) NOT NULL,
  `Aluno_Matricula` INT(9) NOT NULL,
  PRIMARY KEY (`Projeto_Extensao_idProjeto_Extensao`, `Aluno_idAluno`, `Aluno_Matricula`),
  CONSTRAINT `fk_Projeto_Extensao_has_Aluno_Projeto_Extensao1`
    FOREIGN KEY (`Projeto_Extensao_idProjeto_Extensao`)
    REFERENCES `mydb`.`Projeto_Extensao` (`idProjeto_Extensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Extensao_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Matricula`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Projeto_Extensao_has_Aluno_Aluno1_idx` ON `mydb`.`Participa` (`Aluno_idAluno` ASC, `Aluno_Matricula` ASC) VISIBLE;

CREATE INDEX `fk_Projeto_Extensao_has_Aluno_Projeto_Extensao1_idx` ON `mydb`.`Participa` (`Projeto_Extensao_idProjeto_Extensao` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
