-- MySQL Script generated by MySQL Workbench
-- Tue Sep 13 17:27:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Categoria` INT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`endereco_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`endereco_entrega` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`endereco_entrega` (
  `idendereco_entrega` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` CHAR(2) NULL,
  `cep` VARCHAR(10) NULL,
  PRIMARY KEY (`idendereco_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Identificacao` VARCHAR(8) NULL DEFAULT 'Juridica',
  `Endereco` VARCHAR(45) NULL,
  `Cpf_cnpj` VARCHAR(14) NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `endereco_entrega_idendereco_entrega` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Cpf_cnpj_UNIQUE` (`Cpf_cnpj` ASC) VISIBLE,
  INDEX `fk_Cliente_endereco_entrega1_idx` (`endereco_entrega_idendereco_entrega` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_endereco_entrega1`
    FOREIGN KEY (`endereco_entrega_idendereco_entrega`)
    REFERENCES `ecommerce`.`endereco_entrega` (`idendereco_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`tipo_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`tipo_pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`tipo_pedido` (
  `idtipo_pedido` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `ativo` INT NULL,
  PRIMARY KEY (`idtipo_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NULL,
  `Previsao` DATE NULL,
  `Status` CHAR(1) NULL,
  `Data_status` TIMESTAMP NULL,
  `Cod_rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Status` CHAR(1) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `tipo_pedido_idtipo_pedido` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `valor_pedido` DECIMAL(18,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_tipo_pedido1_idx` (`tipo_pedido_idtipo_pedido` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_tipo_pedido1`
    FOREIGN KEY (`tipo_pedido_idtipo_pedido`)
    REFERENCES `ecommerce`.`tipo_pedido` (`idtipo_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `ecommerce`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `Razao_Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(20) NULL,
  PRIMARY KEY (`idfornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_fornecedor` (
  `fornecedor_idfornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`fornecedor_idfornecedor`, `Produto_idProduto`),
  INDEX `fk_fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_Produto_fornecedor_idx` (`fornecedor_idfornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_Produto_fornecedor`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `ecommerce`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `ecommerce`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_Pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`pedido_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`pedido_pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`pedido_pagamento` (
  `idpedido_pagamento` INT NOT NULL AUTO_INCREMENT,
  `vencimento` DATETIME NULL,
  `parcela` INT NULL,
  `valor` DECIMAL(18,2) NULL,
  `documento` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Pedido_tipo_pagamento_idtipo_pagamento` INT NOT NULL,
  PRIMARY KEY (`idpedido_pagamento`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Pedido_tipo_pagamento_idtipo_pagamento`),
  INDEX `fk_pedido_pagamento_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC, `Pedido_tipo_pagamento_idtipo_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_pagamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`forma_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`forma_pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`forma_pagamento` (
  `idforma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `pedido_pagamento_idpedido_pagamento` INT NOT NULL,
  PRIMARY KEY (`idforma_pagamento`, `pedido_pagamento_idpedido_pagamento`),
  INDEX `fk_forma_pagamento_pedido_pagamento1_idx` (`pedido_pagamento_idpedido_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_forma_pagamento_pedido_pagamento1`
    FOREIGN KEY (`pedido_pagamento_idpedido_pagamento`)
    REFERENCES `ecommerce`.`pedido_pagamento` (`idpedido_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
